//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.ExternalModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MieRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MieRequest()
        {
            this.MieRequestItems = new HashSet<MieRequestItem>();
            this.MieResults = new HashSet<MieResult>();
        }
    
        public long RequestID { get; set; }
        public long CandidateID { get; set; }
        public string UserID { get; set; }
        public System.DateTime Date { get; set; }
        public int ClientID { get; set; }
        public Nullable<long> MieRequestID { get; set; }
        public int RequestType { get; set; }
        public Nullable<int> Status { get; set; }
        public bool HasAddInfo { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MieRequestItem> MieRequestItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MieResult> MieResults { get; set; }
    }
}
