//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.ExternalModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VALINFOEntities : DbContext
    {
        public VALINFOEntities()
            : base("name=VALINFOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<MieRequestItem> MieRequestItems { get; set; }
        public virtual DbSet<MieRequest> MieRequests { get; set; }
        public virtual DbSet<MieResult> MieResults { get; set; }
        public virtual DbSet<ProductPriceEntry> ProductPriceEntries { get; set; }
        public virtual DbSet<VerificationProduct> VerificationProducts { get; set; }
    }
}
