//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkPushNotifications
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public Nullable<System.DateTime> NotifcationDateTime { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public string FireBaseID { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
