//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCalendarLibrary
    {
        public int ID { get; set; }
        public Nullable<int> ClientCalendarDetailsID { get; set; }
        public Nullable<int> LibraryID { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    
        public virtual ClientCalendarDetails ClientCalendarDetails { get; set; }
        public virtual Library Library { get; set; }
    }
}
