//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSubMenuMenus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientSubMenuMenus()
        {
            this.ClientSubSubMenus = new HashSet<ClientSubSubMenus>();
        }
    
        public int ID { get; set; }
        public int ClientMenuID { get; set; }
        public string Name { get; set; }
        public string ImageReference { get; set; }
        public string HeadingReference { get; set; }
        public string LinkReference { get; set; }
        public string PopupMessage { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    
        public virtual ClientMenus ClientMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSubSubMenus> ClientSubSubMenus { get; set; }
    }
}
