//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientZendesk
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int ZendeskID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Zendesk Zendesk { get; set; }
    }
}
