//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSubContent
    {
        public int ClientSubContentID { get; set; }
        public int ClientSubSubMenuID { get; set; }
        public int CategoryID { get; set; }
        public int LibraryID { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    
        public virtual Library Library { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual ClientSubSubMenus ClientSubSubMenus { get; set; }
    }
}
