//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCalendarDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientCalendarDetails()
        {
            this.ClientCalendarLibrary = new HashSet<ClientCalendarLibrary>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClientCalendarID { get; set; }
        public string Event { get; set; }
        public Nullable<long> StartTime { get; set; }
        public Nullable<long> EndTime { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string EventName { get; set; }
        public string Type { get; set; }
    
        public virtual ClientCalendar ClientCalendar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCalendarLibrary> ClientCalendarLibrary { get; set; }
    }
}
