//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionsLog
    {
        public int ID { get; set; }
        public string UUID { get; set; }
        public string ConnectionIdentifier { get; set; }
        public string Description { get; set; }
    }
}
