//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MieRequestItem
    {
        public long RequestItemID { get; set; }
        public long RequestID { get; set; }
        public string ItemCode { get; set; }
        public decimal Amount { get; set; }
        public bool IsPackageItem { get; set; }
        public int ClientID { get; set; }
        public Nullable<bool> IsComplete { get; set; }
    
        public virtual MieRequest MieRequest { get; set; }
        public virtual VerificationProduct VerificationProduct { get; set; }
    }
}
