//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileConnections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MobileConnections()
        {
            this.Assessments = new HashSet<Assessments>();
            this.UsageTracker = new HashSet<UsageTracker>();
        }
    
        public int ID { get; set; }
        public int ClientAppID { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string Cellphone { get; set; }
        public string EmailAdress { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Activation { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> DateConnected { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assessments> Assessments { get; set; }
        public virtual ClientApps ClientApps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsageTracker> UsageTracker { get; set; }
    }
}
