//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificationProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VerificationProduct()
        {
            this.MieRequestItems = new HashSet<MieRequestItem>();
            this.ProductPriceEntries = new HashSet<ProductPriceEntry>();
        }
    
        public string ItemCode { get; set; }
        public string Name { get; set; }
        public string IndemnityType { get; set; }
        public string ItemPrice { get; set; }
        public string IndemnityPrompt { get; set; }
        public string IndemnityText { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> HasAttributes { get; set; }
        public Nullable<decimal> SilverPrice { get; set; }
        public Nullable<decimal> GoldPrice { get; set; }
        public Nullable<decimal> PlatinumPrice { get; set; }
        public bool IsArchived { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MieRequestItem> MieRequestItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPriceEntry> ProductPriceEntries { get; set; }
    }
}
