//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.OurProducerServiceLive {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://mie.valinfoapis.co.za/", ConfigurationName="OurProducerServiceLive.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace https://mie.valinfoapis.co.za/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://mie.valinfoapis.co.za/KmiePutResult", ReplyAction="*")]
        CreatorAPI.OurProducerServiceLive.KmiePutResultResponse KmiePutResult(CreatorAPI.OurProducerServiceLive.KmiePutResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://mie.valinfoapis.co.za/KmiePutResult", ReplyAction="*")]
        System.Threading.Tasks.Task<CreatorAPI.OurProducerServiceLive.KmiePutResultResponse> KmiePutResultAsync(CreatorAPI.OurProducerServiceLive.KmiePutResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KmiePutResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KmiePutResult", Namespace="https://mie.valinfoapis.co.za/", Order=0)]
        public CreatorAPI.OurProducerServiceLive.KmiePutResultRequestBody Body;
        
        public KmiePutResultRequest() {
        }
        
        public KmiePutResultRequest(CreatorAPI.OurProducerServiceLive.KmiePutResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://mie.valinfoapis.co.za/")]
    public partial class KmiePutResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int systemType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string result;
        
        public KmiePutResultRequestBody() {
        }
        
        public KmiePutResultRequestBody(string username, string password, int systemType, string result) {
            this.username = username;
            this.password = password;
            this.systemType = systemType;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KmiePutResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KmiePutResultResponse", Namespace="https://mie.valinfoapis.co.za/", Order=0)]
        public CreatorAPI.OurProducerServiceLive.KmiePutResultResponseBody Body;
        
        public KmiePutResultResponse() {
        }
        
        public KmiePutResultResponse(CreatorAPI.OurProducerServiceLive.KmiePutResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://mie.valinfoapis.co.za/")]
    public partial class KmiePutResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KmiePutResultResult;
        
        public KmiePutResultResponseBody() {
        }
        
        public KmiePutResultResponseBody(string KmiePutResultResult) {
            this.KmiePutResultResult = KmiePutResultResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : CreatorAPI.OurProducerServiceLive.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<CreatorAPI.OurProducerServiceLive.WebServiceSoap>, CreatorAPI.OurProducerServiceLive.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CreatorAPI.OurProducerServiceLive.KmiePutResultResponse CreatorAPI.OurProducerServiceLive.WebServiceSoap.KmiePutResult(CreatorAPI.OurProducerServiceLive.KmiePutResultRequest request) {
            return base.Channel.KmiePutResult(request);
        }
        
        public string KmiePutResult(string username, string password, int systemType, string result) {
            CreatorAPI.OurProducerServiceLive.KmiePutResultRequest inValue = new CreatorAPI.OurProducerServiceLive.KmiePutResultRequest();
            inValue.Body = new CreatorAPI.OurProducerServiceLive.KmiePutResultRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.systemType = systemType;
            inValue.Body.result = result;
            CreatorAPI.OurProducerServiceLive.KmiePutResultResponse retVal = ((CreatorAPI.OurProducerServiceLive.WebServiceSoap)(this)).KmiePutResult(inValue);
            return retVal.Body.KmiePutResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreatorAPI.OurProducerServiceLive.KmiePutResultResponse> CreatorAPI.OurProducerServiceLive.WebServiceSoap.KmiePutResultAsync(CreatorAPI.OurProducerServiceLive.KmiePutResultRequest request) {
            return base.Channel.KmiePutResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreatorAPI.OurProducerServiceLive.KmiePutResultResponse> KmiePutResultAsync(string username, string password, int systemType, string result) {
            CreatorAPI.OurProducerServiceLive.KmiePutResultRequest inValue = new CreatorAPI.OurProducerServiceLive.KmiePutResultRequest();
            inValue.Body = new CreatorAPI.OurProducerServiceLive.KmiePutResultRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.systemType = systemType;
            inValue.Body.result = result;
            return ((CreatorAPI.OurProducerServiceLive.WebServiceSoap)(this)).KmiePutResultAsync(inValue);
        }
    }
}
