//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.MieWebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    [System.SerializableAttribute()]
    public partial class Token : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemTypeProxy", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreatorAPI.MieWebservice.ItemType))]
    public partial class ItemTypeProxy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasMetaDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasMetaData {
            get {
                return this.HasMetaDataField;
            }
            set {
                if ((this.HasMetaDataField.Equals(value) != true)) {
                    this.HasMetaDataField = value;
                    this.RaisePropertyChanged("HasMetaData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemType", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    [System.SerializableAttribute()]
    public partial class ItemType : CreatorAPI.MieWebservice.ItemTypeProxy {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowMultipleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndemnityPromptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndemnityTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreatorAPI.MieWebservice.IndemnityType IndemnityTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreatorAPI.MieWebservice.InputGroup[] InputGroupListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowMultiple {
            get {
                return this.AllowMultipleField;
            }
            set {
                if ((this.AllowMultipleField.Equals(value) != true)) {
                    this.AllowMultipleField = value;
                    this.RaisePropertyChanged("AllowMultiple");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndemnityPrompt {
            get {
                return this.IndemnityPromptField;
            }
            set {
                if ((object.ReferenceEquals(this.IndemnityPromptField, value) != true)) {
                    this.IndemnityPromptField = value;
                    this.RaisePropertyChanged("IndemnityPrompt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndemnityText {
            get {
                return this.IndemnityTextField;
            }
            set {
                if ((object.ReferenceEquals(this.IndemnityTextField, value) != true)) {
                    this.IndemnityTextField = value;
                    this.RaisePropertyChanged("IndemnityText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreatorAPI.MieWebservice.IndemnityType IndemnityType {
            get {
                return this.IndemnityTypeField;
            }
            set {
                if ((this.IndemnityTypeField.Equals(value) != true)) {
                    this.IndemnityTypeField = value;
                    this.RaisePropertyChanged("IndemnityType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreatorAPI.MieWebservice.InputGroup[] InputGroupList {
            get {
                return this.InputGroupListField;
            }
            set {
                if ((object.ReferenceEquals(this.InputGroupListField, value) != true)) {
                    this.InputGroupListField = value;
                    this.RaisePropertyChanged("InputGroupList");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndemnityType", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    public enum IndemnityType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Electronic = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manual = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputGroup", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    [System.SerializableAttribute()]
    public partial class InputGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreatorAPI.MieWebservice.InputAttribute[] InputAttributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MultiLineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreatorAPI.MieWebservice.InputAttribute[] InputAttributes {
            get {
                return this.InputAttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.InputAttributesField, value) != true)) {
                    this.InputAttributesField = value;
                    this.RaisePropertyChanged("InputAttributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MultiLine {
            get {
                return this.MultiLineField;
            }
            set {
                if ((this.MultiLineField.Equals(value) != true)) {
                    this.MultiLineField = value;
                    this.RaisePropertyChanged("MultiLine");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputAttribute", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    [System.SerializableAttribute()]
    public partial class InputAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreatorAPI.MieWebservice.InputAttributeType DataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreatorAPI.MieWebservice.InputAttributeDependencyAction DependencyActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependencyValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisplaySequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameLongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameShortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TableKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreatorAPI.MieWebservice.InputAttributeType DataType {
            get {
                return this.DataTypeField;
            }
            set {
                if ((this.DataTypeField.Equals(value) != true)) {
                    this.DataTypeField = value;
                    this.RaisePropertyChanged("DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreatorAPI.MieWebservice.InputAttributeDependencyAction DependencyAction {
            get {
                return this.DependencyActionField;
            }
            set {
                if ((this.DependencyActionField.Equals(value) != true)) {
                    this.DependencyActionField = value;
                    this.RaisePropertyChanged("DependencyAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DependencyCode {
            get {
                return this.DependencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DependencyCodeField, value) != true)) {
                    this.DependencyCodeField = value;
                    this.RaisePropertyChanged("DependencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DependencyValue {
            get {
                return this.DependencyValueField;
            }
            set {
                if ((object.ReferenceEquals(this.DependencyValueField, value) != true)) {
                    this.DependencyValueField = value;
                    this.RaisePropertyChanged("DependencyValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplaySequence {
            get {
                return this.DisplaySequenceField;
            }
            set {
                if ((this.DisplaySequenceField.Equals(value) != true)) {
                    this.DisplaySequenceField = value;
                    this.RaisePropertyChanged("DisplaySequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinLength {
            get {
                return this.MinLengthField;
            }
            set {
                if ((this.MinLengthField.Equals(value) != true)) {
                    this.MinLengthField = value;
                    this.RaisePropertyChanged("MinLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameLong {
            get {
                return this.NameLongField;
            }
            set {
                if ((object.ReferenceEquals(this.NameLongField, value) != true)) {
                    this.NameLongField = value;
                    this.RaisePropertyChanged("NameLong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameShort {
            get {
                return this.NameShortField;
            }
            set {
                if ((object.ReferenceEquals(this.NameShortField, value) != true)) {
                    this.NameShortField = value;
                    this.RaisePropertyChanged("NameShort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Required {
            get {
                return this.RequiredField;
            }
            set {
                if ((this.RequiredField.Equals(value) != true)) {
                    this.RequiredField = value;
                    this.RaisePropertyChanged("Required");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TableKey {
            get {
                return this.TableKeyField;
            }
            set {
                if ((this.TableKeyField.Equals(value) != true)) {
                    this.TableKeyField = value;
                    this.RaisePropertyChanged("TableKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputAttributeType", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    public enum InputAttributeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Integer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Float = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Currency = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Date = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Table = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boolean = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputAttributeDependencyAction", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    public enum InputAttributeDependencyAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Required = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenException", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    [System.SerializableAttribute()]
    public partial class TokenException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Table", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    [System.SerializableAttribute()]
    public partial class Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreatorAPI.MieWebservice.TableValue[] TableValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Key {
            get {
                return this.KeyField;
            }
            set {
                if ((this.KeyField.Equals(value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreatorAPI.MieWebservice.TableValue[] TableValues {
            get {
                return this.TableValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.TableValuesField, value) != true)) {
                    this.TableValuesField = value;
                    this.RaisePropertyChanged("TableValues");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableValue", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    [System.SerializableAttribute()]
    public partial class TableValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((this.DefaultField.Equals(value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Key {
            get {
                return this.KeyField;
            }
            set {
                if ((this.KeyField.Equals(value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgentClientKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgentKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlternateEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FingerPrintHostKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreatorAPI.MieWebservice.RequestItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KnownAsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaidenNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RemoteCaptureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemoteGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RemoteRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RemoteSendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentClientKey {
            get {
                return this.AgentClientKeyField;
            }
            set {
                if ((this.AgentClientKeyField.Equals(value) != true)) {
                    this.AgentClientKeyField = value;
                    this.RaisePropertyChanged("AgentClientKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentKey {
            get {
                return this.AgentKeyField;
            }
            set {
                if ((this.AgentKeyField.Equals(value) != true)) {
                    this.AgentKeyField = value;
                    this.RaisePropertyChanged("AgentKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternateEmail {
            get {
                return this.AlternateEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.AlternateEmailField, value) != true)) {
                    this.AlternateEmailField = value;
                    this.RaisePropertyChanged("AlternateEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientKey {
            get {
                return this.ClientKeyField;
            }
            set {
                if ((this.ClientKeyField.Equals(value) != true)) {
                    this.ClientKeyField = value;
                    this.RaisePropertyChanged("ClientKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FingerPrintHostKey {
            get {
                return this.FingerPrintHostKeyField;
            }
            set {
                if ((this.FingerPrintHostKeyField.Equals(value) != true)) {
                    this.FingerPrintHostKeyField = value;
                    this.RaisePropertyChanged("FingerPrintHostKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreatorAPI.MieWebservice.RequestItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KnownAs {
            get {
                return this.KnownAsField;
            }
            set {
                if ((object.ReferenceEquals(this.KnownAsField, value) != true)) {
                    this.KnownAsField = value;
                    this.RaisePropertyChanged("KnownAs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaidenName {
            get {
                return this.MaidenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MaidenNameField, value) != true)) {
                    this.MaidenNameField = value;
                    this.RaisePropertyChanged("MaidenName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Passport {
            get {
                return this.PassportField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportField, value) != true)) {
                    this.PassportField = value;
                    this.RaisePropertyChanged("Passport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RemoteCaptureDate {
            get {
                return this.RemoteCaptureDateField;
            }
            set {
                if ((this.RemoteCaptureDateField.Equals(value) != true)) {
                    this.RemoteCaptureDateField = value;
                    this.RaisePropertyChanged("RemoteCaptureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RemoteGroup {
            get {
                return this.RemoteGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.RemoteGroupField, value) != true)) {
                    this.RemoteGroupField = value;
                    this.RaisePropertyChanged("RemoteGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RemoteRequest {
            get {
                return this.RemoteRequestField;
            }
            set {
                if ((this.RemoteRequestField.Equals(value) != true)) {
                    this.RemoteRequestField = value;
                    this.RaisePropertyChanged("RemoteRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RemoteSendDate {
            get {
                return this.RemoteSendDateField;
            }
            set {
                if ((this.RemoteSendDateField.Equals(value) != true)) {
                    this.RemoteSendDateField = value;
                    this.RaisePropertyChanged("RemoteSendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestItem", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    [System.SerializableAttribute()]
    public partial class RequestItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreatorAPI.MieWebservice.RequestItemGroup[] GroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IndemnityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemoteItemKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreatorAPI.MieWebservice.RequestItemGroup[] Groups {
            get {
                return this.GroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupsField, value) != true)) {
                    this.GroupsField = value;
                    this.RaisePropertyChanged("Groups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Indemnity {
            get {
                return this.IndemnityField;
            }
            set {
                if ((this.IndemnityField.Equals(value) != true)) {
                    this.IndemnityField = value;
                    this.RaisePropertyChanged("Indemnity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemTypeCode {
            get {
                return this.ItemTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemTypeCodeField, value) != true)) {
                    this.ItemTypeCodeField = value;
                    this.RaisePropertyChanged("ItemTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemoteItemKey {
            get {
                return this.RemoteItemKeyField;
            }
            set {
                if ((this.RemoteItemKeyField.Equals(value) != true)) {
                    this.RemoteItemKeyField = value;
                    this.RaisePropertyChanged("RemoteItemKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestItemGroup", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    [System.SerializableAttribute()]
    public partial class RequestItemGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreatorAPI.MieWebservice.RequestItemGroupLine[] LinesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreatorAPI.MieWebservice.RequestItemGroupLine[] Lines {
            get {
                return this.LinesField;
            }
            set {
                if ((object.ReferenceEquals(this.LinesField, value) != true)) {
                    this.LinesField = value;
                    this.RaisePropertyChanged("Lines");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestItemGroupLine", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    [System.SerializableAttribute()]
    public partial class RequestItemGroupLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreatorAPI.MieWebservice.RequestItemAttribute[] AttributesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreatorAPI.MieWebservice.RequestItemAttribute[] Attributes {
            get {
                return this.AttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributesField, value) != true)) {
                    this.AttributesField = value;
                    this.RaisePropertyChanged("Attributes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestItemAttribute", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
    [System.SerializableAttribute()]
    public partial class RequestItemAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.mie.co.za", ConfigurationName="MieWebservice.IepcvRequestWCF")]
    public interface IepcvRequestWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/GetData", ReplyAction="www.mie.co.za/IepcvRequestWCF/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/GetData", ReplyAction="www.mie.co.za/IepcvRequestWCF/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/GetItemTypes", ReplyAction="www.mie.co.za/IepcvRequestWCF/GetItemTypesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="www.mie.co.za/IepcvRequestWCF/GetItemTypesArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreatorAPI.MieWebservice.TokenException), Action="www.mie.co.za/IepcvRequestWCF/GetItemTypesTokenExceptionFault", Name="TokenException", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
        CreatorAPI.MieWebservice.ItemTypeProxy[] GetItemTypes(CreatorAPI.MieWebservice.Token token);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/GetItemTypes", ReplyAction="www.mie.co.za/IepcvRequestWCF/GetItemTypesResponse")]
        System.Threading.Tasks.Task<CreatorAPI.MieWebservice.ItemTypeProxy[]> GetItemTypesAsync(CreatorAPI.MieWebservice.Token token);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/GetItemType", ReplyAction="www.mie.co.za/IepcvRequestWCF/GetItemTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="www.mie.co.za/IepcvRequestWCF/GetItemTypeArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreatorAPI.MieWebservice.TokenException), Action="www.mie.co.za/IepcvRequestWCF/GetItemTypeTokenExceptionFault", Name="TokenException", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
        CreatorAPI.MieWebservice.ItemType GetItemType(CreatorAPI.MieWebservice.Token token, string itemTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/GetItemType", ReplyAction="www.mie.co.za/IepcvRequestWCF/GetItemTypeResponse")]
        System.Threading.Tasks.Task<CreatorAPI.MieWebservice.ItemType> GetItemTypeAsync(CreatorAPI.MieWebservice.Token token, string itemTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/GetTables", ReplyAction="www.mie.co.za/IepcvRequestWCF/GetTablesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="www.mie.co.za/IepcvRequestWCF/GetTablesArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreatorAPI.MieWebservice.TokenException), Action="www.mie.co.za/IepcvRequestWCF/GetTablesTokenExceptionFault", Name="TokenException", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
        CreatorAPI.MieWebservice.Table[] GetTables(CreatorAPI.MieWebservice.Token token);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/GetTables", ReplyAction="www.mie.co.za/IepcvRequestWCF/GetTablesResponse")]
        System.Threading.Tasks.Task<CreatorAPI.MieWebservice.Table[]> GetTablesAsync(CreatorAPI.MieWebservice.Token token);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/GetTable", ReplyAction="www.mie.co.za/IepcvRequestWCF/GetTableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="www.mie.co.za/IepcvRequestWCF/GetTableArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreatorAPI.MieWebservice.TokenException), Action="www.mie.co.za/IepcvRequestWCF/GetTableTokenExceptionFault", Name="TokenException", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
        CreatorAPI.MieWebservice.Table GetTable(CreatorAPI.MieWebservice.Token token, int tableKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/GetTable", ReplyAction="www.mie.co.za/IepcvRequestWCF/GetTableResponse")]
        System.Threading.Tasks.Task<CreatorAPI.MieWebservice.Table> GetTableAsync(CreatorAPI.MieWebservice.Token token, int tableKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/PutRequest", ReplyAction="www.mie.co.za/IepcvRequestWCF/PutRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="www.mie.co.za/IepcvRequestWCF/PutRequestArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreatorAPI.MieWebservice.TokenException), Action="www.mie.co.za/IepcvRequestWCF/PutRequestTokenExceptionFault", Name="TokenException", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
        int PutRequest(CreatorAPI.MieWebservice.Token token, CreatorAPI.MieWebservice.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/PutRequest", ReplyAction="www.mie.co.za/IepcvRequestWCF/PutRequestResponse")]
        System.Threading.Tasks.Task<int> PutRequestAsync(CreatorAPI.MieWebservice.Token token, CreatorAPI.MieWebservice.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/UploadDocument", ReplyAction="www.mie.co.za/IepcvRequestWCF/UploadDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="www.mie.co.za/IepcvRequestWCF/UploadDocumentArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreatorAPI.MieWebservice.TokenException), Action="www.mie.co.za/IepcvRequestWCF/UploadDocumentTokenExceptionFault", Name="TokenException", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
        void UploadDocument(CreatorAPI.MieWebservice.Token token, int requestKey, byte[] data, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/UploadDocument", ReplyAction="www.mie.co.za/IepcvRequestWCF/UploadDocumentResponse")]
        System.Threading.Tasks.Task UploadDocumentAsync(CreatorAPI.MieWebservice.Token token, int requestKey, byte[] data, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/UploadFingerprint", ReplyAction="www.mie.co.za/IepcvRequestWCF/UploadFingerprintResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="www.mie.co.za/IepcvRequestWCF/UploadFingerprintArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreatorAPI.MieWebservice.TokenException), Action="www.mie.co.za/IepcvRequestWCF/UploadFingerprintTokenExceptionFault", Name="TokenException", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
        int UploadFingerprint(CreatorAPI.MieWebservice.Token token, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/UploadFingerprint", ReplyAction="www.mie.co.za/IepcvRequestWCF/UploadFingerprintResponse")]
        System.Threading.Tasks.Task<int> UploadFingerprintAsync(CreatorAPI.MieWebservice.Token token, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/PutAddInfoText", ReplyAction="www.mie.co.za/IepcvRequestWCF/PutAddInfoTextResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="www.mie.co.za/IepcvRequestWCF/PutAddInfoTextArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreatorAPI.MieWebservice.TokenException), Action="www.mie.co.za/IepcvRequestWCF/PutAddInfoTextTokenExceptionFault", Name="TokenException", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
        void PutAddInfoText(CreatorAPI.MieWebservice.Token token, int requestKey, int credentialKey, int addInfoTypeKey, int addInfoKey, string feedback);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/PutAddInfoText", ReplyAction="www.mie.co.za/IepcvRequestWCF/PutAddInfoTextResponse")]
        System.Threading.Tasks.Task PutAddInfoTextAsync(CreatorAPI.MieWebservice.Token token, int requestKey, int credentialKey, int addInfoTypeKey, int addInfoKey, string feedback);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/PutRequestDocument", ReplyAction="www.mie.co.za/IepcvRequestWCF/PutRequestDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="www.mie.co.za/IepcvRequestWCF/PutRequestDocumentArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreatorAPI.MieWebservice.TokenException), Action="www.mie.co.za/IepcvRequestWCF/PutRequestDocumentTokenExceptionFault", Name="TokenException", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
        void PutRequestDocument(CreatorAPI.MieWebservice.Token token, int requestKey, string name, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/PutRequestDocument", ReplyAction="www.mie.co.za/IepcvRequestWCF/PutRequestDocumentResponse")]
        System.Threading.Tasks.Task PutRequestDocumentAsync(CreatorAPI.MieWebservice.Token token, int requestKey, string name, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/PutAddInfoDocument", ReplyAction="www.mie.co.za/IepcvRequestWCF/PutAddInfoDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="www.mie.co.za/IepcvRequestWCF/PutAddInfoDocumentArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreatorAPI.MieWebservice.TokenException), Action="www.mie.co.za/IepcvRequestWCF/PutAddInfoDocumentTokenExceptionFault", Name="TokenException", Namespace="http://schemas.datacontract.org/2004/07/epcvRequestWCF")]
        void PutAddInfoDocument(CreatorAPI.MieWebservice.Token token, int requestKey, int credentialKey, int addInfoTypeKey, int addInfoKey, string name, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.mie.co.za/IepcvRequestWCF/PutAddInfoDocument", ReplyAction="www.mie.co.za/IepcvRequestWCF/PutAddInfoDocumentResponse")]
        System.Threading.Tasks.Task PutAddInfoDocumentAsync(CreatorAPI.MieWebservice.Token token, int requestKey, int credentialKey, int addInfoTypeKey, int addInfoKey, string name, byte[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IepcvRequestWCFChannel : CreatorAPI.MieWebservice.IepcvRequestWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IepcvRequestWCFClient : System.ServiceModel.ClientBase<CreatorAPI.MieWebservice.IepcvRequestWCF>, CreatorAPI.MieWebservice.IepcvRequestWCF {
        
        public IepcvRequestWCFClient() {
        }
        
        public IepcvRequestWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IepcvRequestWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IepcvRequestWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IepcvRequestWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public CreatorAPI.MieWebservice.ItemTypeProxy[] GetItemTypes(CreatorAPI.MieWebservice.Token token) {
            return base.Channel.GetItemTypes(token);
        }
        
        public System.Threading.Tasks.Task<CreatorAPI.MieWebservice.ItemTypeProxy[]> GetItemTypesAsync(CreatorAPI.MieWebservice.Token token) {
            return base.Channel.GetItemTypesAsync(token);
        }
        
        public CreatorAPI.MieWebservice.ItemType GetItemType(CreatorAPI.MieWebservice.Token token, string itemTypeCode) {
            return base.Channel.GetItemType(token, itemTypeCode);
        }
        
        public System.Threading.Tasks.Task<CreatorAPI.MieWebservice.ItemType> GetItemTypeAsync(CreatorAPI.MieWebservice.Token token, string itemTypeCode) {
            return base.Channel.GetItemTypeAsync(token, itemTypeCode);
        }
        
        public CreatorAPI.MieWebservice.Table[] GetTables(CreatorAPI.MieWebservice.Token token) {
            return base.Channel.GetTables(token);
        }
        
        public System.Threading.Tasks.Task<CreatorAPI.MieWebservice.Table[]> GetTablesAsync(CreatorAPI.MieWebservice.Token token) {
            return base.Channel.GetTablesAsync(token);
        }
        
        public CreatorAPI.MieWebservice.Table GetTable(CreatorAPI.MieWebservice.Token token, int tableKey) {
            return base.Channel.GetTable(token, tableKey);
        }
        
        public System.Threading.Tasks.Task<CreatorAPI.MieWebservice.Table> GetTableAsync(CreatorAPI.MieWebservice.Token token, int tableKey) {
            return base.Channel.GetTableAsync(token, tableKey);
        }
        
        public int PutRequest(CreatorAPI.MieWebservice.Token token, CreatorAPI.MieWebservice.Request request) {
            return base.Channel.PutRequest(token, request);
        }
        
        public System.Threading.Tasks.Task<int> PutRequestAsync(CreatorAPI.MieWebservice.Token token, CreatorAPI.MieWebservice.Request request) {
            return base.Channel.PutRequestAsync(token, request);
        }
        
        public void UploadDocument(CreatorAPI.MieWebservice.Token token, int requestKey, byte[] data, string name) {
            base.Channel.UploadDocument(token, requestKey, data, name);
        }
        
        public System.Threading.Tasks.Task UploadDocumentAsync(CreatorAPI.MieWebservice.Token token, int requestKey, byte[] data, string name) {
            return base.Channel.UploadDocumentAsync(token, requestKey, data, name);
        }
        
        public int UploadFingerprint(CreatorAPI.MieWebservice.Token token, byte[] data) {
            return base.Channel.UploadFingerprint(token, data);
        }
        
        public System.Threading.Tasks.Task<int> UploadFingerprintAsync(CreatorAPI.MieWebservice.Token token, byte[] data) {
            return base.Channel.UploadFingerprintAsync(token, data);
        }
        
        public void PutAddInfoText(CreatorAPI.MieWebservice.Token token, int requestKey, int credentialKey, int addInfoTypeKey, int addInfoKey, string feedback) {
            base.Channel.PutAddInfoText(token, requestKey, credentialKey, addInfoTypeKey, addInfoKey, feedback);
        }
        
        public System.Threading.Tasks.Task PutAddInfoTextAsync(CreatorAPI.MieWebservice.Token token, int requestKey, int credentialKey, int addInfoTypeKey, int addInfoKey, string feedback) {
            return base.Channel.PutAddInfoTextAsync(token, requestKey, credentialKey, addInfoTypeKey, addInfoKey, feedback);
        }
        
        public void PutRequestDocument(CreatorAPI.MieWebservice.Token token, int requestKey, string name, byte[] data) {
            base.Channel.PutRequestDocument(token, requestKey, name, data);
        }
        
        public System.Threading.Tasks.Task PutRequestDocumentAsync(CreatorAPI.MieWebservice.Token token, int requestKey, string name, byte[] data) {
            return base.Channel.PutRequestDocumentAsync(token, requestKey, name, data);
        }
        
        public void PutAddInfoDocument(CreatorAPI.MieWebservice.Token token, int requestKey, int credentialKey, int addInfoTypeKey, int addInfoKey, string name, byte[] data) {
            base.Channel.PutAddInfoDocument(token, requestKey, credentialKey, addInfoTypeKey, addInfoKey, name, data);
        }
        
        public System.Threading.Tasks.Task PutAddInfoDocumentAsync(CreatorAPI.MieWebservice.Token token, int requestKey, int credentialKey, int addInfoTypeKey, int addInfoKey, string name, byte[] data) {
            return base.Channel.PutAddInfoDocumentAsync(token, requestKey, credentialKey, addInfoTypeKey, addInfoKey, name, data);
        }
    }
}
