//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessments
    {
        public int ID { get; set; }
        public int MobileConnectionsID { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public Nullable<int> Question { get; set; }
        public Nullable<int> Answer { get; set; }
    
        public virtual MobileConnections MobileConnections { get; set; }
    }
}
