//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientScreens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientScreens()
        {
            this.ClientScreenContent = new HashSet<ClientScreenContent>();
        }
    
        public int ID { get; set; }
        public int ClientAppID { get; set; }
        public Nullable<int> FontID { get; set; }
        public Nullable<int> ColoursID { get; set; }
        public string Description { get; set; }
        public string Design { get; set; }
        public string LinkReference { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ClientApps ClientApps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreenContent> ClientScreenContent { get; set; }
        public virtual Colours Colours { get; set; }
        public virtual InstalledFonts InstalledFonts { get; set; }
    }
}
