//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.ClientApps = new HashSet<ClientApps>();
            this.ClientRequests = new HashSet<ClientRequests>();
            this.TrustedEmailDomains = new HashSet<TrustedEmailDomains>();
            this.ClientZendesk = new HashSet<ClientZendesk>();
            this.ClientSettings = new HashSet<ClientSettings>();
        }
    
        public int ClientID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNr { get; set; }
        public string Helpline { get; set; }
        public string VatNr { get; set; }
        public string BillingAdress1 { get; set; }
        public string BillingAdress2 { get; set; }
        public string BillingAdress3 { get; set; }
        public string BillilngAdress4 { get; set; }
        public string LinkReference { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientApps> ClientApps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientRequests> ClientRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrustedEmailDomains> TrustedEmailDomains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientZendesk> ClientZendesk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSettings> ClientSettings { get; set; }
    }
}
