//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateSelection
    {
        public int ID { get; set; }
        public int ClientAppID { get; set; }
        public string TemplateType { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual ClientApps ClientApps { get; set; }
    }
}
